name: release

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: CI
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Setup WASM
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: latest
      - name: Run build script
        run: bash build.sh
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

