name: release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: CI
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Setup WASM
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: latest
      - name: Build Release
        run: |
          mkdir public
          wasm-pack build --target web
          mv pkg public/
          cp index.html public/
          ls
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: master
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

